"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
type Item={id:string;title:string;body:string;href:string;read_at:string|null;created_at:string};
export default function NotificationsPage(){const [items,setItems]=useState<Item[]>([]);const [page,setPage]=useState(0);const [hasMore,setHasMore]=useState(false);const [unread,setUnread]=useState(0);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function load(n:number,append=false){setBusy(true);try{const r=await fetch(`/api/notifications?page=${n}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(v=>append?[...v,...d.notifications]:d.notifications);setPage(n);setHasMore(d.hasMore);setUnread(d.unreadCount);}catch(e){setError(e instanceof Error?e.message:"Could not load notifications.");}finally{setBusy(false);}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Load server data after mount.
 useEffect(()=>{void load(0);},[]);
 async function readAll(){await fetch("/api/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"read_all"})});setItems(v=>v.map(i=>({...i,read_at:i.read_at??new Date().toISOString()})));setUnread(0);}
 return <main className="mx-auto flex w-full max-w-3xl flex-col gap-5 px-6 py-12"><div className="flex items-center justify-between"><div><h1 className="font-display text-3xl font-black text-ink">Notifications</h1><p className="mt-1 text-sm text-muted">{unread} unread</p></div>{unread>0&&<button onClick={()=>void readAll()} className="text-sm text-accent">Mark all as read</button>}</div>{error&&<p className="text-sm text-danger">{error}{error.includes("Sign in")&&<Link href="/auth/sign-in?next=%2Fdashboard%2Fnotifications" className="ml-2 underline">Sign in</Link>}</p>}<div className="divide-y divide-border rounded-2xl border border-border bg-surface">{items.map(item=><Link key={item.id} href={item.href} onClick={()=>{if(!item.read_at){void fetch("/api/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({notificationId:item.id})});setUnread(v=>Math.max(0,v-1));}}} className={`block p-4 hover:bg-surface-2 ${item.read_at?"":"bg-accent-soft/5"}`}><strong className="text-sm text-ink">{item.title}</strong><p className="mt-1 text-sm text-muted">{item.body}</p><time className="mt-2 block text-[10px] text-muted">{new Date(item.created_at).toLocaleString()}</time></Link>)}</div>{hasMore&&<button disabled={busy} onClick={()=>void load(page+1,true)} className="self-center rounded-lg border border-border px-4 py-2 text-sm text-ink">{busy?"Loading…":"Load older"}</button>}</main>}
