"use client";
import { useCallback, useEffect, useState } from "react";
import { useAdminSecret } from "@/lib/useAdminSecret";
import { AdminUnlockForm } from "@/components/AdminUnlockForm";
type Claim={id:string;proof:string;created_at:string;claimantEmail:string|null;product:{id:string;name:string;url:string;owner_id:string|null};user_id:string};
export default function AdminFounderClaimsPage(){
 const {secret,unlock,reject}=useAdminSecret();const [claims,setClaims]=useState<Claim[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async(key:string)=>{const r=await fetch("/api/admin/founder-claims",{headers:{"x-admin-secret":key},cache:"no-store"});if(r.status===401){reject();throw new Error("Wrong admin key.");}const d=await r.json();if(!r.ok)throw new Error(d.error);setClaims(d.claims);},[reject]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Load server data after mount.
 useEffect(()=>{if(secret)void load(secret).catch(e=>setError(e.message));},[secret,load]);
 async function handleUnlock(value:string){setBusy(true);try{const r=await fetch("/api/admin/founder-claims",{headers:{"x-admin-secret":value}});if(r.status===401)throw new Error("Wrong admin key.");unlock(value);const d=await r.json();setClaims(d.claims??[]);}catch(e){setError(e instanceof Error?e.message:"Could not unlock admin.");}finally{setBusy(false);}}
 async function decide(claimId:string,action:"approve"|"reject"){setBusy(true);setError("");const r=await fetch("/api/admin/founder-claims",{method:"PATCH",headers:{"Content-Type":"application/json","x-admin-secret":secret!},body:JSON.stringify({claimId,action})});const d=await r.json();if(!r.ok)setError(d.error??"Could not update claim.");else await load(secret!);setBusy(false);}
 if(!secret)return <><AdminUnlockForm onUnlock={handleUnlock} error={error}/>{busy&&<p className="text-center text-xs text-muted">Checking…</p>}</>;
 return <main className="mx-auto flex w-full max-w-4xl flex-col gap-6 px-6 py-12"><div className="flex items-center justify-between"><div><h1 className="font-display text-3xl font-black text-ink">Legacy product claims</h1><p className="mt-1 text-sm text-muted">Review proof before assigning account ownership. Approval is atomic and only succeeds for unclaimed products.</p></div><button onClick={reject} className="text-sm text-muted">Lock</button></div>{error&&<p className="text-sm text-danger">{error}</p>}{claims.length===0&&<p className="rounded-xl border border-dashed border-border p-6 text-sm text-muted">No pending claims.</p>}{claims.map(claim=><article key={claim.id} className="flex flex-col gap-3 rounded-xl border border-border bg-surface p-5"><div><h2 className="font-display text-lg font-bold text-ink">{claim.product.name}</h2><a href={claim.product.url} target="_blank" rel="noopener noreferrer nofollow" className="text-xs text-accent">{claim.product.url}</a><p className="mt-1 text-xs text-muted">Claimant: {claim.claimantEmail??claim.user_id} · {new Date(claim.created_at).toLocaleString()}</p></div><p className="whitespace-pre-wrap rounded-lg bg-surface-2 p-3 text-sm text-ink">{claim.proof}</p><div className="flex gap-2"><button disabled={busy} onClick={()=>void decide(claim.id,"approve")} className="rounded-lg bg-accent px-4 py-2 text-xs font-bold text-accent-ink">Approve ownership</button><button disabled={busy} onClick={()=>void decide(claim.id,"reject")} className="rounded-lg border border-border px-4 py-2 text-xs font-semibold text-ink">Reject</button></div></article>)}</main>
}
