"use client";
import { useCallback, useEffect, useState } from "react";
import { useAdminSecret } from "@/lib/useAdminSecret";
import { AdminUnlockForm } from "@/components/AdminUnlockForm";
type Announcement={id:string;title:string;body:string;status:"draft"|"published";email_requested:boolean;created_at:string;published_at:string|null;delivery:{queued:number;sending:number;sent:number;failed:number;skipped:number}};
export default function AdminAnnouncementsPage(){
 const {secret,unlock,reject}=useAdminSecret();const [items,setItems]=useState<Announcement[]>([]);const [title,setTitle]=useState("");const [body,setBody]=useState("");const [emailRequested,setEmailRequested]=useState(false);const [preview,setPreview]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async(key:string)=>{const r=await fetch("/api/admin/announcements",{headers:{"x-admin-secret":key},cache:"no-store"});if(r.status===401){reject();throw new Error("Wrong admin key.");}const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.announcements);},[reject]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Load server data after mount.
 useEffect(()=>{if(secret)void load(secret).catch(e=>setError(e.message));},[secret,load]);
 async function handleUnlock(value:string){setBusy(true);setError("");try{const r=await fetch("/api/admin/announcements",{headers:{"x-admin-secret":value}});if(r.status===401)throw new Error("Wrong admin key.");unlock(value);const d=await r.json();setItems(d.announcements??[]);}catch(e){setError(e instanceof Error?e.message:"Could not unlock admin.");}finally{setBusy(false);}}
 if(!secret)return <><AdminUnlockForm onUnlock={handleUnlock} error={error}/>{busy&&<p className="pb-8 text-center text-xs text-muted">Checking…</p>}</>;
 const adminSecret = secret;
 async function createDraft(){setBusy(true);setError("");try{const r=await fetch("/api/admin/announcements",{method:"POST",headers:{"Content-Type":"application/json","x-admin-secret":adminSecret},body:JSON.stringify({title,body,emailRequested})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTitle("");setBody("");setPreview(false);await load(adminSecret);}catch(e){setError(e instanceof Error?e.message:"Could not save draft.");}finally{setBusy(false);}}
 async function publish(id:string){setBusy(true);setError("");try{const r=await fetch("/api/admin/announcements",{method:"PATCH",headers:{"Content-Type":"application/json","x-admin-secret":adminSecret},body:JSON.stringify({id,action:"publish"})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load(adminSecret);}catch(e){setError(e instanceof Error?e.message:"Could not publish.");}finally{setBusy(false);}}
 return <main className="mx-auto flex w-full max-w-4xl flex-col gap-8 px-6 py-12"><div className="flex items-center justify-between"><div><h1 className="font-display text-3xl font-black text-ink">Arena announcements</h1><p className="mt-1 text-sm text-muted">Publishing creates one in-app notification per account. Emails go only to users who opted in.</p></div><button onClick={reject} className="text-sm text-muted hover:text-ink">Lock</button></div>{error&&<p className="text-sm text-danger">{error}</p>}
 <section className="flex flex-col gap-4 rounded-2xl border border-border bg-surface p-5"><h2 className="font-display text-lg font-bold text-ink">Create announcement draft</h2><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={140} placeholder="Announcement title" className="rounded-lg border border-border bg-bg px-3 py-2 text-sm text-ink"/><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={5000} rows={5} placeholder="Write a concise Arena update…" className="rounded-lg border border-border bg-bg px-3 py-2 text-sm text-ink"/><label className="flex items-center gap-2 text-sm text-ink"><input type="checkbox" checked={emailRequested} onChange={e=>setEmailRequested(e.target.checked)}/>Also email users subscribed to Arena announcements</label><div className="flex gap-2"><button onClick={()=>setPreview(v=>!v)} className="rounded-lg border border-border px-4 py-2 text-sm font-semibold text-ink">{preview?"Hide preview":"Preview"}</button><button disabled={busy} onClick={()=>void createDraft()} className="rounded-lg bg-accent px-4 py-2 text-sm font-bold text-accent-ink disabled:opacity-50">Save draft</button></div>{preview&&<article className="rounded-xl border border-accent/30 bg-bg p-5"><span className="text-[10px] font-bold uppercase tracking-wide text-accent">THE ARENA · Preview</span><h3 className="mt-2 font-display text-xl font-bold text-ink">{title||"Announcement title"}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-muted">{body||"Announcement body preview"}</p></article>}</section>
 <section className="flex flex-col gap-3"><h2 className="font-display text-xl font-bold text-ink">Recent announcements</h2>{items.map(item=><article key={item.id} className="rounded-xl border border-border bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full bg-surface-2 px-2 py-1 text-[10px] font-bold uppercase text-muted">{item.status}</span><h3 className="mt-2 font-display text-lg font-bold text-ink">{item.title}</h3><p className="mt-1 whitespace-pre-wrap text-sm text-muted">{item.body}</p><p className="mt-2 text-xs text-muted">{item.email_requested?"Email requested":"In-app only"} · {new Date(item.created_at).toLocaleString()}</p></div>{item.status==="draft"&&<button disabled={busy} onClick={()=>void publish(item.id)} className="rounded-lg bg-accent px-3 py-2 text-xs font-bold text-accent-ink disabled:opacity-50">Publish once</button>}</div>{item.status==="published"&&item.email_requested&&<p className="mt-3 text-xs text-muted">Email delivery: {item.delivery.sent} sent · {item.delivery.queued+item.delivery.sending} queued · {item.delivery.failed} failed · {item.delivery.skipped} not subscribed</p>}</article>)}</section></main>
}
