"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
type Analytics = { page_views: number; unique_page_views: number; outbound_clicks: number; unique_outbound_clicks: number };
type Match = { id: string; votes_a: number; votes_b: number; product_a_id: string; product_b_id: string; product_a: { id: string; name: string }; product_b: { id: string; name: string } };
type Product = { id: string; name: string; url: string; status: string; wins: number; losses: number; votesReceived: number; reviews: number; analytics: Analytics; currentMatch: Match | null };
type ClaimCandidate = { id: string; name: string; url: string; status: string; claim: { status: string } | null };
type DashboardData = { products: Product[]; claims: { product_id: string; status: string }[]; campaigns: { id: string; startup_name: string; status: string; submission_target: number }[]; activity: { id: string; title: string; body: string; href: string; created_at: string }[] };
export default function DashboardPage() {
  const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(""); const [claimProof, setClaimProof] = useState<Record<string, string>>({}); const [claiming, setClaiming] = useState<string | null>(null); const [claimQuery, setClaimQuery] = useState(""); const [claimCandidates, setClaimCandidates] = useState<ClaimCandidate[]>([]); const [searchingClaims, setSearchingClaims] = useState(false);
  async function load() { const response = await fetch("/api/dashboard", { cache: "no-store" }); if (response.status === 401) { setError("Sign in to see products linked to your account."); return; } const result = await response.json(); if (!response.ok) { setError(result.error ?? "Could not load dashboard."); return; } setData(result); }
  // eslint-disable-next-line react-hooks/set-state-in-effect -- Load server data after mount.
  useEffect(() => { void load(); }, []);
  async function searchClaims(event: React.FormEvent) { event.preventDefault(); if (claimQuery.trim().length < 2) return; setSearchingClaims(true); const response = await fetch(`/api/dashboard/claims?q=${encodeURIComponent(claimQuery.trim())}`, { cache: "no-store" }); const result = await response.json(); if (response.ok) { const claims = result.claims as { product_id: string; status: string }[]; setClaimCandidates((result.products as Omit<ClaimCandidate, "claim">[]).map((product) => ({ ...product, claim: claims.find((claim) => claim.product_id === product.id) ?? null }))); } else setError(result.error ?? "Could not search legacy products."); setSearchingClaims(false); }
  async function requestClaim(productId: string) { setClaiming(productId); setError(""); const response = await fetch("/api/dashboard/claims", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ productId, proof: claimProof[productId] ?? "" }) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Could not submit claim."); else { setClaimProof((previous) => ({ ...previous, [productId]: "" })); await load(); await searchClaims({ preventDefault() {} } as React.FormEvent); } setClaiming(null); }
  return <main className="mx-auto flex w-full max-w-6xl flex-col gap-8 px-6 py-12">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-3xl font-black text-ink">My Arena</h1><p className="mt-1 text-sm text-muted">Your products, duel activity, and audience metrics.</p></div><Link href="/dashboard/settings" className="rounded-lg border border-border bg-surface px-4 py-2 text-sm font-semibold text-ink hover:border-accent">Notification settings</Link></div>
    {error && <div className="rounded-lg border border-danger/30 bg-danger/5 p-4 text-sm text-danger">{error}{!data && <Link className="ml-2 underline" href={`/auth/sign-in?next=${encodeURIComponent("/dashboard")}`}>Sign in</Link>}</div>}
    {!data ? <p className="text-sm text-muted">Loading your Arena…</p> : <>
      <section className="flex flex-col gap-4"><h2 className="font-display text-xl font-bold text-ink">My products <span className="text-sm font-normal text-muted">({data.products.length})</span></h2>
        {data.products.length === 0 ? <p className="rounded-xl border border-dashed border-border p-6 text-sm text-muted">No products are linked to your account yet. New signed-in submissions will appear here.</p> : data.products.map((product) => {
          const match = product.currentMatch; const isA = match?.product_a_id === product.id; const rival = match ? (isA ? match.product_b : match.product_a) : null;
          return <article key={product.id} className="rounded-2xl border border-border bg-surface p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/product/${product.id}`} className="font-display text-lg font-bold text-ink hover:text-accent">{product.name}</Link><p className="mt-1 text-xs text-muted">{product.status.toUpperCase()} · {product.wins} wins · {product.losses} losses · {product.reviews} reviews</p></div>{match ? <Link href={`/duel/${match.id}`} className="rounded-lg bg-accent px-3 py-2 text-xs font-bold text-accent-ink">Open live duel</Link> : <span className="rounded-full bg-surface-2 px-3 py-1 text-xs text-muted">{product.status === "active" ? "Waiting for rival" : product.status}</span>}</div>
            {match && <p className="mt-3 text-sm text-muted">Versus <strong className="text-ink">{rival?.name}</strong> · {product.votesReceived} votes received · <Link href={`/duel/${match.id}`} className="text-accent hover:underline">Live duel</Link></p>}
            <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5"><Metric label="Votes received" value={String(product.votesReceived)} /><Metric label="Page views" value={product.analytics.page_views.toLocaleString()} hint={`${product.analytics.unique_page_views.toLocaleString()} unique visitors/day`} /><Metric label="Website clicks" value={product.analytics.outbound_clicks.toLocaleString()} hint={`${product.analytics.unique_outbound_clicks.toLocaleString()} unique visitors/day`} /><Metric label="Wins" value={String(product.wins)} /><Metric label="Reviews" value={String(product.reviews)} /></div>
            {product.status === "champion" && <p className="mt-3 text-sm font-semibold text-accent">🏆 Current category champion</p>}
            {product.status === "eliminated" && <p className="mt-2 text-xs text-muted">Last duel status: eliminated. View the product page for history and revive options.</p>}

          </article>;
        })}
      </section>
      <section className="flex flex-col gap-3"><h2 className="font-display text-xl font-bold text-ink">Claim a legacy product</h2><p className="text-sm text-muted">Search products that are not linked to an account. Claims are reviewed by an Arena admin before ownership is connected.</p><form onSubmit={(event) => void searchClaims(event)} className="flex flex-wrap gap-2"><input value={claimQuery} onChange={(event) => setClaimQuery(event.target.value)} minLength={2} maxLength={80} placeholder="Product name or website" className="min-w-0 flex-1 rounded-lg border border-border bg-surface px-3 py-2 text-sm text-ink"/><button disabled={searchingClaims || claimQuery.trim().length < 2} className="rounded-lg bg-accent px-4 py-2 text-sm font-bold text-accent-ink disabled:opacity-50">{searchingClaims ? "Searching…" : "Search"}</button></form>{claimCandidates.map((product) => <article key={product.id} className="rounded-xl border border-border bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/product/${product.id}`} className="font-semibold text-ink hover:text-accent">{product.name}</Link><p className="mt-1 text-xs text-muted">{product.url}</p></div>{product.claim ? <span className="text-xs text-muted">Claim {product.claim.status}</span> : <span className="text-xs text-muted">Unclaimed</span>}</div>{!product.claim && <div className="mt-3 flex flex-col gap-2"><textarea value={claimProof[product.id] ?? ""} onChange={(event) => setClaimProof((previous) => ({ ...previous, [product.id]: event.target.value }))} rows={2} maxLength={2000} placeholder="Explain how you can verify ownership (10–2,000 characters)." className="rounded-lg border border-border bg-bg p-3 text-sm text-ink"/><button disabled={claiming === product.id} onClick={() => void requestClaim(product.id)} className="self-start rounded-lg bg-accent px-4 py-2 text-xs font-bold text-accent-ink disabled:opacity-50">{claiming === product.id ? "Submitting…" : "Submit claim for review"}</button></div>}</article>)}</section>
      {data.campaigns.length > 0 && <section className="flex flex-col gap-3"><h2 className="font-display text-xl font-bold text-ink">Get Listed campaigns</h2>{data.campaigns.map((campaign) => <Link key={campaign.id} href={`/get-listed/campaigns/${campaign.id}`} className="rounded-xl border border-border bg-surface p-4 hover:border-accent"><strong className="text-ink">{campaign.startup_name}</strong><span className="ml-2 text-xs text-muted">{campaign.status.replaceAll("_", " ")} · {campaign.submission_target} listings</span></Link>)}</section>}
      <section className="flex flex-col gap-3"><h2 className="font-display text-xl font-bold text-ink">Recent activity</h2>{data.activity.length ? <ul className="divide-y divide-border rounded-xl border border-border bg-surface">{data.activity.map((item) => <li key={item.id} className="p-4"><Link href={item.href} className="text-sm font-semibold text-ink hover:text-accent">{item.title}</Link><p className="mt-1 text-xs text-muted">{item.body}</p></li>)}</ul> : <p className="text-sm text-muted">Your Arena activity will appear here.</p>}</section>
    </>}
  </main>;
}
function Metric({ label, value, hint }: { label: string; value: string; hint?: string }) { return <div className="rounded-lg bg-surface-2 p-3"><span className="block text-[10px] font-semibold uppercase tracking-wide text-muted">{label}</span><strong className="mt-1 block font-mono text-lg text-ink">{value}</strong>{hint && <small className="block text-[10px] text-muted">{hint}</small>}</div>; }
